/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fpliu_android_ndk_pkg_prefab_example_ffmpeg_MainActivity */

#ifndef _Included_com_fpliu_android_ndk_pkg_prefab_example_ffmpeg_MainActivity
#define _Included_com_fpliu_android_ndk_pkg_prefab_example_ffmpeg_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fpliu_android_ndk_pkg_prefab_example_ffmpeg_MainActivity
 * Method:    test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fpliu_android_ndk_pkg_prefab_example_ffmpeg_MainActivity_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
